spring.application.name=embalseschs

# jOOQ
spring.datasource.driver-class-name=org.postgresql.Driver
# Esto ayuda a jOOQ a saber que hablas con Postgres antes de conectar
spring.jooq.sql-dialect=POSTGRES
# Opcional: Ayuda si tienes problemas con nombres de tablas en mayúsculas/minúsculas
spring.jooq.render-name-case=lower_if_unquoted

# JPA / Hibernate (Inhabilitar completamente)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Configuración de HikariCP
# Evita que las conexiones mueran silenciosamente
# Indispensable para que el Pooler no cierre la conexión por "idleness"
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.leak-detection-threshold=5000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=4