spring.application.name=embalseschs

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jooq.sql-dialect=POSTGRES
spring.jooq.render-name-case=lower_if_unquoted

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.leak-detection-threshold=5000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=4