spring.application.name=embalseschs

# CRÍTICO: evita que Hibernate intente tocar el schema
spring.jpa.hibernate.ddl-auto=none

# jOOQ
spring.jooq.sql-dialect=POSTGRES

# HikariCP
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.validation-timeout=5000